import Link from 'next/link';
import {Chrome} from '../../../components/chrome';
import {CopyButton} from '../../../components/copy-button';
import {config} from '../../../lib/genlayer/config';
import {getRelation,getStudyVersion,listAllEdges} from '../../../lib/genlayer/data-source';

export default async function ReceiptPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;let claim=null,edge=null,source=null,target=null,error='';
  try{claim=await getRelation(id);if(!claim)throw new Error('Claim receipt not found.');[source,target]=await Promise.all([getStudyVersion(String(claim.source_id),Number(claim.source_version)),getStudyVersion(String(claim.target_id),Number(claim.target_version))]);if(!source||!target)throw new Error('Pinned receipt study data is unavailable.');if(claim.status==='EDGE_ACCEPTED'){const edges=await listAllEdges(String(claim.source_id));edge=edges.find(value=>String(value.claim_id)===String(claim!.claim_id))??null;if(!edge)throw new Error('Accepted claim has no authoritative edge record.')}}
  catch(e){error=e instanceof Error?e.message:'Receipt unavailable.'}
  const rows=claim&&source&&target?[['NETWORK','StudioNet'],['CHAIN ID','61999'],['CONTRACT ADDRESS',config.contractAddress],['EDGE ID',edge?String(edge.edge_id):'No accepted edge'],['CLAIM ID',String(claim.claim_id)],['SOURCE ID / VERSION',String(claim.source_id)+' / '+String(claim.source_version)],['SOURCE MANIFEST DIGEST',source.manifest_digest],['TARGET ID / VERSION',String(claim.target_id)+' / '+String(claim.target_version)],['TARGET MANIFEST DIGEST',target.manifest_digest],['CLAIMANT',claim.claimant],['CLAIMED RELATION',claim.claimed_relation],['FINAL RELATION',claim.final_relation||'None'],['OUTCOME CLASS',claim.outcome_class||'Pending'],['EVIDENCE URL',claim.evidence_url],['EVIDENCE DIGEST',claim.evidence_digest],['DECISION RATIONALE',claim.rationale||'Not adjudicated'],['FINAL STATUS',claim.status]]:[];
  return <main><Chrome/><div className="page-shell max-w-4xl"><p className="eyebrow">{edge?'Accepted edge receipt':'Claim receipt'} · {id}</p><h1 className="page-title">Authoritative provenance receipt</h1>{error?<div className="panel p-8 mt-6">{error}</div>:<section className="panel p-6 mt-6"><dl className="grid sm:grid-cols-[210px_1fr] gap-0">{rows.map(([label,value])=><div className="contents" key={label}><dt className="eyebrow border-b border-[#d8dde1] py-3">{label}</dt><dd className="hash border-b border-[#d8dde1] py-3">{value}</dd></div>)}</dl><div className="flex gap-2 mt-5 flex-wrap"><CopyButton value={JSON.stringify(Object.fromEntries(rows),null,2)} label="Copy receipt"/><a className="button secondary" target="_blank" rel="noreferrer" href={config.explorer}>Open StudioNet explorer</a></div></section>}<Link href={'/relations/'+id} className="inline-block mt-6 underline">Return to relation</Link></div></main>
}
