export type Study={study_id:string|number;registrant:string;title:string;question_text:string;method_text:string;conclusion_text:string;manifest_url:string;manifest_digest:string;publication_ref:string;version:string|number;created_at:string|number};
export type RelationClaim={claim_id:string|number;source_id:string|number;target_id:string|number;source_version:string|number;target_version:string|number;claimant:string;claimed_relation:string;evidence_url:string;evidence_digest:string;status:string;final_relation:string;outcome_class:string;rationale:string;reviewed_at:string|number};
export type Edge={edge_id:string|number;claim_id:string|number;source_id:string|number;target_id:string|number;source_version:string|number;target_version:string|number;relation_code:string;rationale:string;accepted_at:string|number};
export type Neighbor={study_id:string|number;field_kind:string;version:string|number;distance:number;title:string};

const record=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value);
export function parseStudy(value:unknown):Study{if(!record(value)||typeof value.title!=='string'||typeof value.question_text!=='string'||typeof value.method_text!=='string'||typeof value.conclusion_text!=='string')throw new Error('Malformed study response');return value as Study}
export function parseRelationClaim(value:unknown):RelationClaim{if(!record(value)||typeof value.claim_id!=='number'&&typeof value.claim_id!=='string'||typeof value.status!=='string'||typeof value.outcome_class!=='string')throw new Error('Malformed relation response');return value as RelationClaim}
export function parseEdge(value:unknown):Edge{if(!record(value)||value.edge_id===undefined||value.claim_id===undefined||typeof value.relation_code!=='string')throw new Error('Malformed edge response');return value as Edge}
export function parseNeighbor(value:unknown):Neighbor{if(!record(value)||value.study_id===undefined||typeof value.field_kind!=='string'||typeof value.title!=='string')throw new Error('Malformed neighbor response');const distance=Number(value.distance);if(!Number.isFinite(distance))throw new Error('Malformed neighbor distance');return {...value,distance} as Neighbor}
