'use client';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {Chrome} from '../../../components/chrome';
import {useWallet} from '../../../components/wallet-provider';
import {writeContract} from '../../../lib/genlayer/contract';
import {useState,Suspense} from 'react';

function RelationForm(){const q=useSearchParams();const w=useWallet();const [source,setSource]=useState('');const [target,setTarget]=useState(q.get('target')??'');const [relation,setRelation]=useState('DIRECT_REPLICATION');const [evidence,setEvidence]=useState('');const [digest,setDigest]=useState('');const [state,setState]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!source||!target||source===target){setState('Choose two distinct study IDs.');return}if(!w.account){setState('Connect an injected wallet first.');return}setState('Submitting claim…');try{const r=await writeContract(w.account,'claim_relation',[Number(source),Number(target),relation,evidence,digest]);setState(`Claim submitted: ${r.hash}`)}catch(err){setState(err instanceof Error?err.message:'Claim failed.')}};return <main><Chrome/><div className="max-w-5xl mx-auto p-6 lg:p-12"><p className="mono text-xs text-[#1d5aa5]">RELATION COMPARISON</p><h1 className="serif text-4xl mt-2">Place two immutable versions side by side.</h1><form onSubmit={submit} className="mt-8"><div className="grid md:grid-cols-2 gap-4"><label className="panel p-5"><span className="mono text-xs">SOURCE STUDY ID</span><input required value={source} onChange={e=>setSource(e.target.value)} className="w-full border-b border-[#303438] bg-transparent py-3 mono outline-none"/></label><label className="panel p-5"><span className="mono text-xs">TARGET STUDY ID</span><input required value={target} onChange={e=>setTarget(e.target.value)} className="w-full border-b border-[#303438] bg-transparent py-3 mono outline-none"/></label></div><div className="panel p-5 mt-4"><span className="mono text-xs">CLAIMED RELATION</span><select value={relation} onChange={e=>setRelation(e.target.value)} className="block mt-3 border border-[#303438] bg-transparent p-3"><option>DIRECT_REPLICATION</option><option>MATERIAL_VARIANT</option><option>EXTENSION</option><option>CONTRADICTORY_RESULT</option><option>INCOMPARABLE</option></select><input required value={evidence} onChange={e=>setEvidence(e.target.value)} className="w-full border-b border-[#303438] bg-transparent py-3 mt-5 outline-none" placeholder="https://…"/><input required value={digest} onChange={e=>setDigest(e.target.value)} className="w-full border-b border-[#303438] bg-transparent py-3 mono outline-none" placeholder="sha256 digest"/></div><button className="mt-5 bg-[#1d5aa5] text-white px-4 py-3">Submit relation claim</button>{state&&<p className="mt-4 border-l-2 border-[#b44f36] pl-3 text-sm">{state}</p>}</form><Link href="/" className="inline-block mt-8 underline text-sm">Back to graph</Link></div></main>}
export default function NewRelation(){return <Suspense fallback={<main className="p-8">Loading relation sheet…</main>}><RelationForm/></Suspense>}
