import Link from 'next/link';
import {Chrome} from '../../../components/chrome';
import {AdjudicateAction} from '../../../components/adjudicate-action';
import {getRelation,getStudyVersion,listAllEdges,searchRelated} from '../../../lib/genlayer/data-source';

export default async function RelationPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;let claim=null,source=null,target=null,neighbors=[] as Awaited<ReturnType<typeof searchRelated>>,edgeId:string|number|undefined,error='';
  try{claim=await getRelation(id);if(!claim)throw new Error('Relation claim not found.');const [question,method,conclusion]=await Promise.all(['QUESTION','METHOD','CONCLUSION'].map(field=>searchRelated(String(claim!.source_id),field,4)));[source,target]=await Promise.all([getStudyVersion(String(claim.source_id),Number(claim.source_version)),getStudyVersion(String(claim.target_id),Number(claim.target_version))]);neighbors=[...question,...method,...conclusion];if(!source||!target)throw new Error('Pinned study version not found.');if(claim.status==='EDGE_ACCEPTED'){const edges=await listAllEdges(String(claim.source_id));edgeId=edges.find(value=>String(value.claim_id)===String(claim!.claim_id))?.edge_id}}
  catch(e){error=e instanceof Error?e.message:'Relation read unavailable.'}
  return <main><Chrome/><div className="page-shell"><p className="eyebrow">Scientific method matrix · claim {id}</p>{error?<div className="panel p-8 mt-6"><h1>{error}</h1></div>:claim&&source&&target&&<><div className="flex justify-between gap-4 flex-wrap items-end"><h1 className="page-title">Independent evidence review</h1><span className="network-state">{claim.status}</span></div><div className="matrix mt-6"><strong>Field</strong><strong>Source · #{claim.source_id} v{claim.source_version}</strong><strong>Target · #{claim.target_id} v{claim.target_version}</strong>{[['Question','question_text'],['Method','method_text'],['Conclusion','conclusion_text']].flatMap(([label,key])=>[<strong key={key+'-l'}>{label}</strong>,<span key={key+'-s'}>{source[key as keyof typeof source]}</span>,<span key={key+'-t'}>{target[key as keyof typeof target]}</span>])}</div><section className="panel p-5 mt-5"><h2>Claim and evidence</h2><dl className="grid sm:grid-cols-[170px_1fr] gap-3 mt-4 text-sm"><dt>Claimant</dt><dd className="hash">{claim.claimant}</dd><dt>Claimed relation</dt><dd>{claim.claimed_relation}</dd><dt>Evidence URL</dt><dd><a target="_blank" rel="noreferrer" className="text-[#1d5aa5] underline" href={claim.evidence_url}>{claim.evidence_url}</a></dd><dt>Evidence digest</dt><dd className="hash">{claim.evidence_digest}</dd><dt>Outcome class</dt><dd>{claim.outcome_class||'Pending'}</dd><dt>Final relation</dt><dd>{claim.final_relation||'None'}</dd><dt>Decision rationale</dt><dd>{claim.rationale||'Not yet adjudicated.'}</dd></dl>{claim.status==='EVIDENCE_INVALID'&&<p className="status-box">The immutable evidence failed integrity validation. Create a new claim with correct evidence.</p>}{claim.status==='INSUFFICIENT'&&<p className="status-box">Validators found insufficient semantic basis for a substantive relation.</p>}<AdjudicateAction claimId={id} status={claim.status}/><Link className="button secondary inline-block mt-4" href={'/receipts/'+id}>{edgeId?'Open accepted edge '+edgeId:'Open claim receipt'}</Link></section><section className="panel p-5 mt-5"><h2>Semantic context</h2><p className="muted">Vector distance retrieves context. It is not validator confidence.</p>{neighbors.map(n=><Link className="ledger-row" key={n.study_id+'-'+n.version+'-'+n.field_kind} href={'/studies/'+n.study_id}>#{n.study_id} v{n.version} · {n.field_kind} · distance {n.distance}</Link>)}</section></>}</div></main>
}
