'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';
import {STUDIONET_CHAIN_ID_HEX} from '../lib/genlayer/constants';
type Wallet={account:string|null;chainId:string|null;connect:()=>Promise<void>;disconnect:()=>Promise<void>;switchNetwork:()=>Promise<void>;wrongNetwork:boolean;connecting:boolean;error:string|null};
const C=createContext<Wallet>({account:null,chainId:null,connect:async()=>{},disconnect:async()=>{},switchNetwork:async()=>{},wrongNetwork:false,connecting:false,error:null});
const target=STUDIONET_CHAIN_ID_HEX;
function readable(error:unknown){const m=error instanceof Error?error.message:String(error);if(/user rejected|denied|rejected/i.test(m))return 'Connection request declined.';return m.length>90?`${m.slice(0,87)}…`:m}
export function WalletProvider({children}:{children:React.ReactNode}){const [account,setAccount]=useState<string|null>(null);const [chainId,setChainId]=useState<string|null>(null);const [connecting,setConnecting]=useState(false);const [error,setError]=useState<string|null>(null);
const connect=async()=>{const e=(window as any).ethereum;if(!e){setError('No injected wallet detected.');return}setConnecting(true);setError(null);try{const a=await e.request({method:'eth_requestAccounts'});if(!Array.isArray(a))throw new Error('Wallet returned an invalid account response.');setAccount(a[0]??null);setChainId(await e.request({method:'eth_chainId'}));}catch(err){setError(readable(err));}finally{setConnecting(false)}};
const disconnect=async()=>{const e=(window as any).ethereum;setError(null);if(e){try{await e.request({method:'wallet_revokePermissions',params:[{eth_accounts:{}}]})}catch(_err){/* Wallets without revocation support fall back to local state. */}}setAccount(null);setChainId(null)};
const switchNetwork=async()=>{const e=(window as any).ethereum;if(!e){setError('No injected wallet detected.');return}try{await e.request({method:'wallet_switchEthereumChain',params:[{chainId:target}]});setChainId(await e.request({method:'eth_chainId'}));setError(null)}catch(err){setError(readable(err))}};
useEffect(()=>{const e=(window as any).ethereum;if(!e)return;let alive=true;const restore=async()=>{try{const a=await e.request({method:'eth_accounts'});const c=await e.request({method:'eth_chainId'});if(alive){setAccount(Array.isArray(a)?a[0]??null:null);setChainId(typeof c==='string'?c:null)}}catch(_err){/* read-only restoration is best effort */}};restore();const ac=(a:string[])=>setAccount(a?.[0]??null);const ch=(c:string)=>setChainId(c);const dc=()=>{setAccount(null);setChainId(null)};e.on?.('accountsChanged',ac);e.on?.('chainChanged',ch);e.on?.('disconnect',dc);return()=>{alive=false;e.removeListener?.('accountsChanged',ac);e.removeListener?.('chainChanged',ch);e.removeListener?.('disconnect',dc)}},[]);
return <C.Provider value={useMemo(()=>({account,chainId,connect,disconnect,switchNetwork,wrongNetwork:!!chainId&&chainId.toLowerCase()!==target,connecting,error}),[account,chainId,connecting,error])}>{children}</C.Provider>}
export const useWallet=()=>useContext(C);
